### ISSUE TITLE
version of llvm required by cmake is unclear

### ISSUE THREAD

**Issue by jlapeyre** [eclipse/xacc#129]
cmake complains "LLVM version too old" and "Could not find any Clang libraries in".

I am following the build instructions on the github README.md
```
cmake .. -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m -DXACC_BUILD_TESTS=TRUE
```
The error messages are
```
Could not find LLVM: LLVM version too old: 8.0.1
```
and
```
Could not find any Clang libraries in
```
I modified `FindLLVM.cmake` to print the minimum required version of LLVM, which is in `LLVM_FIND_VERSION`, and has the value `9.0.0`.  Version 8.0.1 was released in July 2019. I am unable to find where `LLVM_FIND_VERSION` is set. In any case it should probably appear in the error message. But, this may be an upstream issue.

The clang libraries are searched for in `LLVM_LIBRARY_DIRS` which is apparently empty.

I don't know where `LLVM_LIBRARY_DIRS` is set either.

I would not be surprised if both of these errors were due to a misconfigured clang on my machine.

**Comment by amccaskey** [comment]
Hey @jlapeyre 

Thank you for pointing this out, the CMake message could be more clear. The code in tools/compiler is actually a prototype for single-source quantum kernels in C++. That code is going to be moved to our single-source compiler, qcor, in the near future. I will update the qcor docs and cmake output to better show the required version for Clang/LLVM (which is 9, but we may be able to lower it to 8, but nothing below 8). 

But do note that the messages you quoted above are not errors, they are just messages informing you that Cmake could not find an appropriate Clang version, so tools/compiler is not going to be built.

**Comment by amccaskey** [comment]
LLVM no longer a dependency of XACC, checkout https://github.com/ornl-qci/qcor
