### ISSUE TITLE
Quick start docker image name is out of date

### ISSUE THREAD

**Issue by jordanperr** [eclipse/xacc#168]
The docker image referenced in the quick start guide, "xacc-dev," is no longer visible through docker hub. As a new user it is unclear to me which image I should use instead.

https://xacc.readthedocs.io/en/latest/developers.html#quick-start-with-docker

**Comment by amccaskey** [comment]
The docker images are in a state of being updated - we're moving to building them through a continuous deployment pipeline. You could pull the xacc/xacc image instead. That one needs to be updated though. If you would like a more up to date image, you can build the image manually like this:

```bash
$ cd docker/ci/ubuntu1804/master 
$ docker build -t xacc/local-dev .
$ docker run -it xacc/local-dev bash 
```

hope that helps!

**Comment by amccaskey** [comment]
this has been updated. docker images are being deployed nightly and read the docs page has been updated.
