### ISSUE TITLE
Missing documentation on setting runtime parameters.

### ISSUE THREAD

**Issue by aravindhv10** [eclipse/xacc#182]
Hi,

I wanted to know how to change parameters inside XASM code, for instance:
`
__qpu__ void bell(qbit q,double theta) {
H(q[0]);
CX(q[0],q[1]);
CX(q[0],q[1]);
CX(q[0], q[1]);
Rx(q[0],theta);
Measure(q[0]);
Measure(q[1]);
}
`
now how do I actually set "theta" before executing the above function ?
In the C++ api, I find a function `IR::setRuntimeVariables` which takes as argument `HeterogeneousMap`, does this do the job ? How do I achieve the same in python api ?

Thanks

**Comment by amccaskey** [comment]
Hey @aravindhv10, once you have that kernel as a `CompositeInstruction`, you can call `CompositeInstruction::operator()(std::vector<double> params)`

```cpp
auto compiler = xacc::getCompiler("xasm");
auto IR = compiler->compile(R"(__qpu__ void bell(qbit q,double theta) { 
H(q[0]); 
CX(q[0],q[1]); 
CX(q[0],q[1]); 
CX(q[0], q[1]); 
Rx(q[0],theta); 
Measure(q[0]); 
Measure(q[1]); 
})");
auto kernel = IR->getComposite("bell");

auto evaled_kernel = (*kernel)({2.2});
std::cout << evaled_kernel->toString() << "\n";
```
Hope that helps, let me know if you need anything else. I'll put a task on me to add this to the Basis documentation page.

**Comment by aravindhv10** [comment]
Hi, Thanks for your extremely quick reply !
Do you also know how to implement this in python ?

**Comment by amccaskey** [comment]
Sure
```python
compiler = xacc.getCompiler('xasm')
ir = compiler.compile('''__qpu__ void bell(qbit q,double theta) { 
H(q[0]); 
CX(q[0],q[1]); 
CX(q[0],q[1]); 
CX(q[0], q[1]); 
Rx(q[0],theta); 
Measure(q[0]); 
Measure(q[1]); 
}
''')
kernel = ir.getComposite('bell')
evaled = kernel.eval([2.2])
print(evaled)
```

You could also use the `xacc.qasm()` call
```python
xacc.qasm('''
.compiler xasm
.qbit q
.circuit bell
.parameters theta
H(q[0]); 
CX(q[0],q[1]); 
CX(q[0],q[1]); 
CX(q[0], q[1]); 
Rx(q[0],theta); 
Measure(q[0]); 
Measure(q[1]); 
}
''')
bell = xacc.getCompiled('bell')
evaled = bell.eval([2.2])
print(evaled)
```

**Comment by aravindhv10** [comment]
Thanks ! That worked.
