### ISSUE TITLE
Combining subcircuits

### ISSUE THREAD

**Issue by aswanthkrishna** [eclipse/xacc#183]
Hi,
I want to pass the output of one circuit as the input of the next. for instance, I have two circuits,`circ1 = xacc.getCompiled('circ1') circ2 = xacc.getCompiled('circ2')`. It will be enough for me to be able to make a bigger circuit by combining them or be able to execute them on the same register one after the other. Both circuits have no measurements. How can I achieve this?

**Comment by amccaskey** [comment]
Here's an easy way to do it

```python
xasm = xacc.getCompiler('xasm')
ir1 = xasm.compile('''__qpu__ void foo(qbit q) {
    H(q[0]);
}''')
ir2 = xasm.compile('''__qpu__ void bar(qbit q) {
    foo(q);
    CX(q[0],q[1]);
}''')
bar = ir2.getComposite('bar')
print(bar)
```

**Comment by aswanthkrishna** [comment]
Thank you so much.
