### ISSUE TITLE
Large number of arguments to XASM function and clearing compilation database.

### ISSUE THREAD

**Issue by aravindhv10** [eclipse/xacc#184]
Hi,

How do we pass a large number of arguments (if possible, dynamically variable) to a XASM function ? On a related note, is it possible to clear the compiled database of xasm functions so that xasm functions with same name can be repeatedly generated (in a dynamic and automated way) with different parameters ?

Thanks
Aravind

**Comment by amccaskey** [comment]
You can treat a single incoming parameter as a vector:
```python
xacc.qasm('''
.compiler xasm
.parameters x
.circuit foo
.qbit q
Rx(q[0], x[0]);
Ry(q[0], x[1]);
...
Rz(q[0], x[25]);
''')
```

does that help? 

As for clearing the compiled functions, not right now. But I can add one and you can pull and rebuild.

**Comment by aravindhv10** [comment]
Hi, @amccaskey 

     Yes, it worked thanks!
     As for using same set of instructions with different parameters, I managed to achieve similar results using the IRProvider functions directly, thanks again !

Regards
Aravind
