### ISSUE TITLE
Parsing issue - Antlr update

### ISSUE THREAD

**Issue by danclaudino** [eclipse/xacc#186]
Antlr update 4.7.2->4.8 causes generating observables from string to parse incorrectly.

**Comment by danclaudino** [comment]
Here is a python MWE:

`import xacc`
`geom = '''`
`H  0.000000   0.0      0.0`
`H   0.0        0.0  .7474`
`'''`
`H = xacc.getObservable('pyscf', {'basis': 'sto-3g', 'geometry': geom})`
`print(H.toString()) # causes xacc to throw [XACC Error] Invalid Fermion Operator source: line 1:1153 extraneous input '-' expecting {REAL, INT}`
`newH = xacc.getObservable('fermion', H.toString())`
`print(newH.toString()) # no errors, but only prints one-particle operators`

**Comment by amccaskey** [comment]
This has been fixed in latest from master.
