### ISSUE TITLE
How to get the Optmised circuit after QAOA 

### ISSUE THREAD

**Issue by aswanthkrishna** [eclipse/xacc#199]
The current QAOA algorithm returns opt-Val and opt-params. Can I get measurement results of the form {'bitstring':'counts'} or the optimized circuit from it?

**Comment by amccaskey** [comment]
Hey @aswanthkrishna, for the bit strings, depends on what Accelerator you are using and what initialization parameters you provide it. What does your getAccelerator() call look like? If you are using an Accelerator that produces bit strings, then those bit strings will be collected on the children of the AcceleratorBuffer that you are using.

As for getting the optimized circuit: If you have the optimized parameters, I would just re-create the qaoa circuit and evaluate it at those parameters. Something like this

```python
provider = xacc.getIRProvider('quantum')
qaoa = xacc.asComposite(xacc.createInstruction('qaoa', {}))
params = xacc.HeterogeneousMap()
params.insert('nbQubits', n_q)
params.insert('nbSteps', n_steps)
params.insert('cost-ham', cost_observable)
params.insert('ref-ham', ref_hamiltonian) # optional
qaoa.expand(m)

opt_circ = qaoa.eval(opt_params)
```

Let me know if you need this for C++ and not Python. I can post that here too.

**Comment by aswanthkrishna** [comment]
Thank you for you help @amccaskey . I am currently using the 'aer' accelerator. 
`qpu = xacc.getAccelerator('aer')
`
also` when I run this code, I am getting the following error. 

> AttributeError: module 'xacc' has no attribute 'createInstruction'

**Comment by amccaskey** [comment]
sorry, should be ``provider.createInstruction('qaoa', {})``

**Comment by aswanthkrishna** [comment]
Thank you so much for your help!  what is 'ref-ham' here?
