### ISSUE TITLE
Doubt in using HWE Ansatz

### ISSUE THREAD

**Issue by obliviateandsurrender** [eclipse/xacc#200]
I'm trying to use HWE ansatz, but the output circuit always comes out to be blank. 

xacc.qasm(f'''
    .compiler xasm
    .circuit ansatz
    .parameters t0
    .qbit q
    hwe(q, t0, { {"nq", {num_qubits}}, {"layers", {layers}}, {"coupling",  str(coupling) }});
''')

where the coupling is of type List[Tuple(Int, Int)], num_qubits and layers are integers. 

Preview:
![image](https://user-images.githubusercontent.com/23234279/84355083-a3a86400-abdf-11ea-8b9d-4534168d626e.png)

I couldn't find any documentation regarding using this. Any help will be appreciated.

**Comment by amccaskey** [comment]
Looks like you've found a bug in how the XASM compiler processes circuit generator options. We'll work on a fix for this. In the meantime, you could generate the hwe ansatz with for loops or with the hwe generator directly. Check this out:

```python
xacc.qasm('''
.compiler xasm
.circuit ansatz
.parameters x
.qbit q
for (int i = 0; i < 2; i++) {
    Rx(q[i],x[i]);
    Rz(q[i],x[2+i]);
}
CX(q[0],q[1]);
for (int i = 0; i < 2; i++) {
    Rx(q[i], x[i+4]);
    Rz(q[i], x[i+4+2]);
    Rx(q[i], x[i+4+4]);
}
''')
```
```python

provider = xacc.getIRProvider('quantum')
hwe = xacc.asComposite(provider.createInstruction('hwe'))

options = xacc.HeterogeneousMap()
options.insert('nq', 2)
options.insert('layers', 2)
options.insert('coupling', [[0,1]])

hwe.expand(options)

print(hwe)
```

**Comment by joehellmers** [comment]
Is anyone working on this?  I could give it a shot.
