### ISSUE TITLE
AttributeError: '_pyxacc.Accelerator' object has no attribute 'createBuffer'

### ISSUE THREAD

**Issue by sheecegardezi** [eclipse/xacc#206]
I was trying to run this [example](https://xacc.readthedocs.io/en/latest/obsolete/tutorials.html?highlight=tnqvm#simple-teleportation-kernel) with tnqvm as accelerator but it runs into the following error:

`AttributeError: '_pyxacc.Accelerator' object has no attribute 'createBuffer'`

```
import xacc
xacc.Initialize()
qpu = xacc.getAccelerator('tnqvm') 
qubits = qpu.createBuffer('q',3)

@xacc.qpu(accelerator=qpu)
def teleport(buffer):
   X(0)
   H(1)
   CNOT(1,2)
   CNOT(0,1)
   CNOT(1,2)
   CNOT(2,0)
   Measure(2, 0)

teleport(qubits)
print(qubits)
xacc.Finalize()
```

**Comment by amccaskey** [comment]
Hmm. Not sure how you made it to that doc page, it is old. Note that the URL relative path has 'obsolete' in it. The createBuffer() method is no longer on Accelerator. You could achieve the same code like this 
```python
import xacc
qpu = xacc.getAccelerator('qpp', {'shots':1024})
qubits = xacc.qalloc(3)

xacc.qasm('''
.compiler xasm
.circuit teleport
.qbit q
X(q[0]);
H(q[1]);
CX(q[1],q[2]);
CX(q[0],q[1]);
CX(q[1],q[2]);
CX(q[2], q[0]);
Measure(q[2]);
''')
teleport = xacc.getCompiled('teleport')
qpu.execute(qubits, teleport)
print(qubits)
counts = qubits.getMeasurementCounts()
```
Also note here I used the QPP simulator to show bit string counts, TNQVM (by default) will just get you expectation values.

**Comment by sheecegardezi** [comment]
I quickly wend through the examples in the new docs; I noticed that circuits are build using a string input to compiler(eg. xasm, openqasm... ) to generate circuits. Is natively writing circuits in python deprecated ?

**Comment by amccaskey** [comment]
No you can still write something like this
```python

qpu = xacc.getAccelerator('qpp', {'shots':1024})
qubits = xacc.qalloc(3)

@xacc.qpu(accelerator=qpu)
def foo(q):
    X(q[0])
    H(q[1])
    CX(q[1],q[2])
    CX(q[0],q[1])
    CX(q[1],q[2])
    CX(q[2], q[0])
    Measure(q[2])

foo(qubits)
print(qubits)
```

There are just more features available from using the string API. The native python functions are still more a prototype that will be elevated to a first-class feature in the future. But try it out and push it and let us know where it breaks 😄

**Comment by sheecegardezi** [comment]
Perfect thanks so much. I will defiantly be testing it out over the coming days.
