### ISSUE TITLE
Clarification regarding QAOA implementation

### ISSUE THREAD

**Issue by aswanthkrishna** [eclipse/xacc#224]
The original qaoa algorithm introduced in the paper by E Farhi uses the same beta parameter for all the qubits in mixer Hamiltonian propagator , same gamma for all the terms in cost Hamiltonian propagator.

> ham = xacc.getObservable('pauli', '-5.0 - 0.5 Z0 - 1.0 Z2 + 0.5 Z3 + 1.0 Z0 Z1 + 2.0 Z0 Z2 + 0.5 Z1 Z2 + 2.5 Z2 Z3')
> nbParamsPerStep = 7 + 4

from this code block from the qaoa_example.py I think we are using different betas for each qubit in the mixer and different gammas for each term in cost Hamiltonian. Am i right?
if yes , does this provide any advantage over the original approach?

**Comment by tnguyen-ornl** [comment]
Hi @aswanthkrishna,

Yes, you're right.

The QAOA implementation in XACC used an `extended` parameterization scheme whereby each operator in both the cost and mixer Hamiltonians has its own angle.

Since the goal of the ansatz circuit is to produce a quantum state that optimizes the cost function, we have some degree of flexibility in choosing how to parametrize a QAOA problem. 
If we choose a smaller set of parameters, where the optimization landscape has a lower dimension at the expense of higher circuit depth. If we choose a larger set, we can explore a wider set of quantum states with lower circuit depth, of course, at the expense of higher optimization dimension. 

In the implementation, we opted for the extended scheme which is a superset of the standard scheme (bundle a group of betas and gammas per step into one parameter) for maximum flexibility and extensibility.

**Comment by aswanthkrishna** [comment]
Thank you for the quick reply @tnguyen-ornl 
typically wont this make the optimisation landscape complex and introduce more local minimas? in my experiment the value to which qaoa converges is highly sensitive to the starting point. Can you suggest some ways that i can solve this?

**Comment by tnguyen-ornl** [comment]
I don't have a concrete answer to the local minima problem.
I totally agree with you about the sensitivity to initial parameters. In fact, this has been studied quite extensively. There are some heuristic initialization strategies that were shown to be much better than random initialization.
For example, see arXiv:1812.01041

**Comment by aswanthkrishna** [comment]
Thanks for the reference. Also how will i go about bundling the parameters as u suggested with the current implementation? I want to compare the performance of both approaches. thank you for your patience.

**Comment by tnguyen-ornl** [comment]
This is a Python example that shows how we can bundle params and also apply a simple initialization strategy:
```
import xacc,sys, numpy as np

# == Demonstrated custom QAOA API ==

# Get access to the desired QPU
qpu = xacc.getAccelerator('qpp')

# Construct the Hamiltonian as an XACC PauliOperator
# This Hamiltonian corresponds to the QUBO problem:
# y = -5x_1 -3x_2 -8x_3 -6x_4 + 4x_1x_2 + 8x_1x_3 + 2x_2x_3 + 10x_3x_4
ham = xacc.getObservable('pauli', '-5.0 - 0.5 Z0 - 1.0 Z2 + 0.5 Z3 + 1.0 Z0 Z1 + 2.0 Z0 Z2 + 0.5 Z1 Z2 + 2.5 Z2 Z3')

# We need 4 qubits
buffer = xacc.qalloc(4)

# The number of steps (often referred to as 'p' parameter): 
# alternating layers of mixer and cost Hamiltonian exponential.
nbSteps = 8

# Example: using vanilla QAOA (nbParams =  2 * nbSteps)
nbTotalParams = 2 * nbSteps

# Init params: 
# Example: using an *Annealing* initial params:
# i.e. gamma = (1 - s(t)); beta = s(t)
# ramping down gamma and ramping up beta
s = lambda step : float(step/nbSteps)
initParams = []
for i in range(nbSteps):
    # Convention: beta then gamma
    initParams.append(s(i))
    initParams.append(1.0 - s(i))
# Get an optimizer/stepper
opt = xacc.getOptimizer('nlopt', { 'initial-parameters': initParams })

# Create the QAOA algorithm
qaoa = xacc.getAlgorithm('QAOA', {
                        'accelerator': qpu,
                        'observable': ham,
                        'optimizer': opt,
                        'steps': nbSteps,
                        })

# Define optimization function:
def qaoa_vanilla(x):
    assert len(x) == nbTotalParams
    # NOTE: here, we bundle betas and gammas per step into one beta and one gamma
    # i.e. the vanila QAOA.
    # Convention: betas then gammas
    NUM_BETAS_PER_STEP = 7
    NUM_GAMMAS_PER_STEP = 4
    flattenedParams = []
    for i in range(nbSteps):
        flattenedParams += (NUM_BETAS_PER_STEP * [x[2*i]])
        flattenedParams += (NUM_GAMMAS_PER_STEP * [x[2*i + 1]])

    assert len(flattenedParams) == nbSteps * (NUM_GAMMAS_PER_STEP + NUM_BETAS_PER_STEP)
    energy = qaoa.execute(buffer, flattenedParams)
    print("Energy = ", energy[0])
    return energy[0]

enery, params = opt.optimize(qaoa_vanilla, nbTotalParams)
print('Min QUBO value = ', enery)
```

**Comment by aswanthkrishna** [comment]
Thank you!
