### ISSUE TITLE
createPulseModel still supported?

### ISSUE THREAD

**Issue by pkairys** [eclipse/xacc#230]
I'm trying to get the XACC/QuaC examples working and I keep running into issues when I run

`model=createPulseModel()`

returns

`AttributeError: module 'xacc' has no attribute 'createPulseModel'`

Is this an error with my instillation (I'm using a docker container)? Or has the API changed?

Thanks!

**Comment by amccaskey** [comment]
did you update your PYTHONPATH to point to the XACC install? 

```bash
$ export PYTHONPATH=$PYTHONPATH:$HOME/.xacc
```

**Comment by amccaskey** [comment]
Also what docker image are you using?

**Comment by pkairys** [comment]
Yea I've updated the PYTHONPATH and I have no problem running other XACC examples (such as opt.py and dueteronH2.py et al.). 

I'm using my own docker image because I wanted to run jupyterlab instead of Theia. But it is based off of[ your dev-quac dockerfile](https://github.com/eclipse/xacc/blob/master/docker/deploy/dev_quac/Dockerfile). See below

`FROM xacc/deploy-base
WORKDIR /home/dev
RUN cd /home/dev && git clone --recursive https://github.com/eclipse/xacc && cd xacc && mkdir build && cd build \
    && cmake .. \
    && make -j$(nproc) install \
    && cd ../../ && git clone https://github.com/ornl-qci/tnqvm && cd tnqvm && mkdir build && cd build \
    && cmake .. -DXACC_DIR=~/.xacc && make -j$(nproc) install \
    && cd /home/dev && git clone -b maint https://bitbucket.org/petsc/petsc petsc && cd petsc \
    && export PETSC_DIR=${PWD} && export PETSC_ARCH=linux-gnu-c-complex \
    && ./configure --with-scalar-type=complex --download-mpich --download-fblaslapack=1 \
                   --with-debugging=no COPTFLAGS=-O3 CXXOPTFLAGS=-O3 FOPTFLAGS=-O3 --with-64-bit-indices \
    && make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all \
    && cd /home/dev && git clone -b xacc-integration https://github.com/ORNL-QCI/QuaC.git \
    && cd QuaC && mkdir build && cd build \
    && cmake .. -DPETSC_DIR=${PETSC_DIR} -DPETSC_ARCH=linux-gnu-c-complex -DXACC_DIR=~/.xacc \
    && make install

RUN python3 -m pip install jupyterlab pandas seaborn

ENV SHELL=/bin/bash
ENV PYTHONPATH "${PYTHONPATH}:/root/.xacc:/root/.local/lib/python3.6/site-packages/psi4/lib"`

Actually I am now seeing an error on startup:

`[xacc-logger] [error] [XACC Error] Failure initializing XACC Plugin Registry - Bundle#9 start failed: libmpi.so.12: cannot open shared object file: No such file or directory`

Perhaps this error is the reason.

**Comment by amccaskey** [comment]
can you share the image on dockerhub so I can run it without having to build? Just sent you an invite to the xacc slack for quicker communication...

**Comment by pkairys** [comment]
Thanks to Alex's help I've figured out that I had mounted a volume onto my docker container at /home/dev, removing critical libraries. This wasn't an XACC bug, just user error.
