### ISSUE TITLE
Python Segmentation Faults

### ISSUE THREAD

**Issue by eugescu** [eclipse/xacc#24]
kernel.nParameters() and kernel.getName() lead to segmentation faults in pyxacc

**Comment by amccaskey** [comment]
Hey @eugescu check out latest commit https://github.com/eclipse/xacc/commit/f71e64d3f267c085388b59f03e81a09934150c43, should fix these seg faults.

**Comment by amccaskey** [comment]
I also updated your python script in the schwinger repo...
