### ISSUE TITLE
Help with windows installation

### ISSUE THREAD

**Issue by aswanthkrishna** [eclipse/xacc#248]
Is it possible to build xacc on windows?

**Comment by tnguyen-ornl** [comment]
Hi @aswanthkrishna, 

At the moment, we don't support *native* Windows build, e.g., using the MSVC compiler.

However, if you are using Windows 10, you can enable [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (Windows Subsystem for Linux) feature and you can compile and use XACC within WSL. 

The [build procedure](https://xacc.readthedocs.io/en/latest/install.html#prerequisites) for WSL is the same as that of the corresponding Linux distro.

If you prefer an IDE environment, you can consider installing [Docker WSL backend](https://docs.docker.com/docker-for-windows/wsl/).

With Docker installed on Windows, you can use built-in Eclipse Theia IDE by clicking the Gitpod icon under XACC [QuickStart](https://github.com/eclipse/xacc#quick-start).

**Comment by aswanthkrishna** [comment]
Thank you @tnguyen-ornl  
I want to freeze my program as an exe file and run on windows. Is it possible? 
Really appreciate all your help!

**Comment by tnguyen-ornl** [comment]
Unfortunately, we don't support native Windows build, so you cannot create a `.exe` file from XACC on Windows.

**Comment by amccaskey** [comment]
I think the only way to get something like this is to package your application as a docker image with an appropriate entry point defined. You could then provide you application as a script that executes the correct docker commands.

**Comment by aswanthkrishna** [comment]
Thank you @amccaskey . I will try to do that.
