### ISSUE TITLE
New placement strategies

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#263]
https://github.com/ORNL-QCI/TriQ 

https://github.com/iic-jku/minimal_ibm_qx_mapping

https://github.com/ysiraichi/enfield

Putting this here so we keep track of them. @tnguyen-ornl

**Comment by tnguyen-ornl** [comment]
I think the second placement strategy (https://github.com/iic-jku/minimal_ibm_qx_mapping) was implemented in `enfield` (https://github.com/ysiraichi/enfield/blob/master/include/enfield/Transform/Allocators/ChallengeWinnerQAllocator.h) 

We probably will only need to integrate `enfield` then.

**Comment by tnguyen-ornl** [comment]
Enfield-based placement has been implemented in our forked [branch](https://github.com/ORNL-QCI/enfield/tree/xacc)

There are a few placement strategies that we can use. The full list is [here](https://github.com/ORNL-QCI/enfield/blob/xacc/xacc/tests/EnfieldPlacementTester.cpp#L8)

The [minimal qx mapping](https://github.com/iic-jku/minimal_ibm_qx_mapping) is called 'ChallengeWinnerQAllocator' (`Q_chw`).
