### ISSUE TITLE
IBM rest API communication issues 

### ISSUE THREAD

**Issue by eugescu** [eclipse/xacc#29]
Below are two examples of HTTP status line issues I have encountered in the last 24 hrs. 

**EX1:**
Job Response: RUNNING[2018-04-09 16:51:12.680] [xacc-logger] [info] IBM Accelerator caught exception while calling restClient->get() - Failed to read HTTP status line
[2018-04-09 16:51:12.680] [xacc-logger] [info] Retrying HTTP Get.
Job Response: RUNNINGAssertion failed: (false), function operator[], file /Users/edq/Library/Python/3.6/lib/python/site-packages/xacc-0.1.0-py3.6-macosx-10.11-x86_64.egg/include/rapidjson/include/rapidjson/document.h, line 1103.
Abort trap: 6

**EX2:** 
----> 1 energy = lambda angles: vqe.execute(xaccOp, **{'task':'compute-energy',                                     'ansatz':IR_fun, 'accelerator':acc,                                     'vqe-params':str(angles)[1:len(str(angles))-1]
      2                                     })
 RuntimeError: Failed to read HTTP status line

**Comment by amccaskey** [comment]
Ex1 makes me wonder if IBM updated their JSON string for checking job status...
