### ISSUE TITLE
std::any and GNU stdc++ bug for RTTI and dynamic loading

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#292]
Just wanted to document this. 

In versions of GCC below 7.5 and 8.4 there is a bug whereby std::any_cast fails in the presence of dynamic library loading. This affects our HeterogeneousMap data structure. 

Here's a reference to the bug fix https://github.com/gcc-mirror/gcc/commit/683f9728e8f54bff4b798dead54c5c4275079158#diff-1d4ec2cbbc8c2e33d4a80c2bc5554db6R438

This leaves GCC version 7.5, 8.4, 9.3, 10.1, 10.2 as valid versions.

**Comment by amccaskey** [comment]
One question - did we only see this bug for the case of passing a void* to the HetMap in the HPC Virt plugin?

**Comment by tnguyen-ornl** [comment]
The `deuteronH2.py` example in the current **Gitpod** image failed b/c of this bug as well. It is using GCC version 8.3.

**Comment by amccaskey** [comment]
Was just trying to test it, can confirm that.

**Comment by amccaskey** [comment]
with 8.2.0, the c++ tests all seem to pass.

**Comment by amccaskey** [comment]
https://github.com/tnguyen-ornl/xacc/blob/efa12a271cac722c970b4fb9ec82077d3b100507/xacc/utils/heterogeneous.hpp

**Comment by tnguyen-ornl** [comment]
fyi, seems like the `std::any` fix was backported to minor versions also.
e.g. on Redhat with `gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)`, `<any>` header **does** contain the fix. 
So we may need to check on the GCC release date when debugging this issue.
