### ISSUE TITLE
Mac and Linux Python Wheels

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#30]
We need to create binary builds as python wheels to make it easy for users to pip install xacc and friends.

**Comment by amccaskey** [comment]
This is made difficult by our dependence on openssl

**Comment by jayjaybillings** [comment]
What's the license on RestClient-CPP?

**Comment by amccaskey** [comment]
Looks like we need to make sure we don't actually link to ${PYTHON_LIBRARY} and set up to lookup the symbols at runtime

https://github.com/davisking/dlib/pull/701

https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

https://github.com/davisking/dlib/commit/4a4fd91a26f93e8e2a486f50c7817661876a5dba
