### ISSUE TITLE
Trying to create standalone C++ program to execute circuits

### ISSUE THREAD

**Issue by joehellmers** [eclipse/xacc#302]
Hello.  I'm trying to create a simple C++ program with which I can create and execute a quantum circuit.

I'm adding include paths, but I got to a point where I need variants.hpp, but I see multiple versions in my built xacc local git clone.

Can somebody let me know which file I should be using?

Better yet, give me an example makefile or cmake setup to do what I'd like to do?

My ultimate goal is to implement some nuclear physics algorithms on multiple platforms (IBM, Rigetti, etc).

Thanks.

**Comment by tnguyen-ornl** [comment]
Hi,

This is a typical example of a `CMakeLists.txt` to build an XACC-based application:
https://github.com/ORNL-QCI/xacc_application_example/blob/master/CMakeLists.txt
At the very minimal, we need to `find_package(XACC REQUIRED)` and  link to `xacc::xacc`.

Also, that git [repo](https://github.com/ORNL-QCI/xacc_application_example) is a very good example to get started.

Hope that this may help you.

**Comment by joehellmers** [comment]
Thanks!  That's exactly what I needed.
