### ISSUE TITLE
Consider switch to RestClient-CPP

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#31]
This could help with deployment in #30 

https://github.com/mrtazz/restclient-cpp

**Comment by jayjaybillings** [comment]
What's the license on RestClient-CPP?

**Comment by jayjaybillings** [comment]
Word. That was the major benefit of what we wrote with the original updater: All you needed was libcurl.

**Comment by amccaskey** [comment]
Yea that was nice 👍 

With this we would have users 
```bash
brew/dnf/apt-get install curl-devel (or whatever it is)
``` 
to a system path thats always in LD_LIBRARY_PATH

Then 

```bash
pip install xacc --user
```

to install the os-specific pre-built wheel.
