### ISSUE TITLE
$XACC_DIR/include/xacc/version causes problems for projects that use C++20 #include <version>

### ISSUE THREAD

**Issue by simon-ty** [eclipse/xacc#333]
For our project, which uses XACC and Boost, there is a conflict where Boost (boost/config/detail/select_stdlib_config.hpp) has lines like 
`#include <version>`

Since our include path for headers has XACC's paths first, it resolves to XACC's <version> (whereas Boost wants to pickup the Standard Library header with this name).

Is it possible to give include/xacc/version a different name instead?

**Comment by amccaskey** [comment]
Yea sure thing. I'll take care of that now. Will rename to xacc_version

**Comment by amccaskey** [comment]
@simon-ty everything fixed for you now?

**Comment by simon-ty** [comment]
Hi Alex,
Yes thank you - it is working ok now.
regards
Simon
