### ISSUE TITLE
Quimb Quantum Circuit Simulator as Accelerator Impl

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#352]
We should integrate Quimb as a new Accelerator https://quimb.readthedocs.io/en/latest/tensor-circuit.html 

This can be done using pybind11 and its embedded interpreter.

**Comment by aswanthkrishna** [comment]
Is there a documentation for doing something like this? i want to integrate [https://github.com/QCoDeS/Qcodes](url) as an accelerator to execute pulses on our hardware. their API is in python

**Comment by amccaskey** [comment]
Yea I wrote this awhile back https://aide-qc.github.io/deploy/developers/implement_accelerator/

**Comment by aswanthkrishna** [comment]
Is it possible to write this entirely in python? similar to [https://github.com/eclipse/xacc/blob/master/python/plugins/cirq/cirq_accelerator.py](url)
