### ISSUE TITLE
Observable grouping for QAOA-MAXCUT

### ISSUE THREAD

**Issue by tnguyen-ornl** [eclipse/xacc#399]
Max-cut Hamiltonian only contains terms of Z products; hence could theoretically be observed in 1 measurement,
e.g., measure all bits and compute exp-val for each term from the bitstring distribution.

Related to https://github.com/eclipse/xacc/issues/354, which is a more generic grouping task.

**Comment by Milos9304** [comment]
Yes, I agree this is a very important enhancement that needs to be implemented. I've done the implementation for my project and I aim to create a PR when I clean and test everything. The way I did it is that in the qaoa algorithm I generated a kernel which applies the troterrization steps as usual and then peform many multiple-qubit measurements #421 which do not collapse the state but calculate the expectation value of the qubits in each of the hamiltonian term and save them to the buffer.

However, my code does ugly modifications, e.g. modifying Measure gate. Hence I propose to implement a new Gate, ExpVal gate (I will create a new issue), which is not a real-world gate, but which would make the qaoa simulations run much faster (I observed 15x speedup at my pc).

I do not understand the connection to #354 , or better said I don't understand what criterion is meant to be used for observable grouping. Perhaps that could lead to a smoother approach than modifying measure gates / implementing ExpVal gates.
