### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by chMoussa** [eclipse/xacc#42]
Hello,

I have a segmentation fault from getMeasurementStrings and getMeasurementCounts.
I installed XACC and plugings with pip on Docker images. 
I am attaching the printing of a simple script and the script.

![segfault](https://user-images.githubusercontent.com/18176484/43465385-e005e360-94a2-11e8-9048-519c6b0ba4cd.PNG)

import pyxacc as xacc
import sys

def hello(acc="ibm",backendinput="ibmq_qasm_simulator"):
    xacc.Initialize(["--compiler","quil"])
    accelerator = acc
    backend = backendinput

    qpu = xacc.getAccelerator(accelerator)
    nqbits = 2

    xacc.setOption(acc+"-backend",backend)
    # code commented is for setting
    # the number of trials one run the circuit (default 1024)
    # One can set any option that come with the accelerator
    # xacc.setOption("ibm-shots","1024")
    # xacc.setOption("rigetti-trial","1024")

    qreg = qpu.createBuffer("qreg",nqbits)

    src = """__qpu__ bell(AcceleratorBuffer b){
    H 0
    CNOT 0 1
    MEASURE 0 [0]
    MEASURE 1 [1]
    }
    """

    program = xacc.Program(qpu,src)
    program.build()

    k = program.getKernel("bell")
    k.execute(qreg,[])

    print(qreg.getMeasurementStrings())
    print(qreg.getMeasurementCounts())
    xacc.Finalize()

if __name__ == "__main__":

    if len(sys.argv) == 3:
        hello(sys.argv[1],sys.argv[2])
    else:
        hello()

**Comment by amccaskey** [comment]
@chMoussa Thanks for filing this issue. We're going to look into it today and see what we find. It may be that the Pip wheels need to be updated.

**Comment by amccaskey** [comment]
@chMoussa I have uploaded an updated xacc-ibm wheel to PyPi. You can now run 

```bash
$ python -m pip install --upgrade xacc-ibm
```
Let us know if that gets rid of your bug. 

Note you should see it upgrade to version 0.1.1

**Comment by amccaskey** [comment]
Hey Charles, 

Notice that you don't have the IBM plugin installed (does not say 'Installed plugin 'xacc-ibm-*'). Also notice that your XACC install is in your ~/.local/* directory, so you installed the XACC wheel with --user. If you run pip install xacc --user, then you must run all plugin installs with --user. 

I suggest
```bash
$ python -m pip uninstall xacc-ibm (which should remove it from wherever it was installed)
$ python -m pip install xacc-ibm --user --no-cache
```
You should see that it downloads and install version 0.1.1.

**Comment by chMoussa** [comment]
I run the pip upgrade and it told me it was upgraded to 0.1.1.
But anyway I run your last commands and I finally got rid of the segmentation fault.

**Comment by chMoussa** [comment]
Can we do the same for rigetti ?

![hellorigetti](https://user-images.githubusercontent.com/18176484/43489316-3f9f2888-94e2-11e8-834b-b57cfa512274.PNG)

**Comment by chMoussa** [comment]
Working well now thanks
