### ISSUE TITLE
xacc::getAccelerator("ibm") automatic backend selection based on jobs in the queue

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#441]
It would be cool to have a backend specification for the IBM Accelerator that set at initialization time the physical backend as the one that had the least number of jobs in the queue. Something like 
```cpp
auto qpu = xacc::getAccelerator("ibm", {{"backend","lowest-queue-count"}, {"n-qubits", N}});
```
Note the optional need to specify how many qubits your job will need so that you don't get back a backend with too few qubits. 

Ultimately this will require an update to the IBMAccelerator::initialize() method to pull the backend info from the remote server using the Rest Client, and pick out the backend to use accordingly.

**Comment by flatslm** [comment]
Hi, I am interested with this project and would like to work on this issue (it looks like a "least_busy()" method from Qiskit).
It seems I'll have a few questions about about testing this functionality (Which mode It is possible? Auto, or only manual?) and about detailed content of 'HeterogeneousMap' parameter.

**Comment by tnguyen-ornl** [comment]
Hi @flatslm 

The `HeterogeneousMap` parameter which is passed to `IBMAccelerator::initialize` and subsequently `updateConfiguration` is like a Python `dict` (containing key-value pairs). 
Hence, for this task, we just need to handle two additional keys as described above.

Yea, it is similar to the `least_busy()` method from Qiskit and the idea is to implement a similar logic via the REST API.
In `initialize`, for example, at some point, you'll see that we have a list of `your_available_backends` and info about all these backends. 
You could use that to determine which ones have enough qubits and query the queue status to select the `lowest-queue-count` device.

Hope this helps!

**Comment by flatslm** [comment]
I created a PR draft with minimal functionality (https://github.com/eclipse/xacc/pull/451 - will be cleaned etc.), and have a few questions:
1.	The following filtration of backends is possible:
-	By reservations from ‘/bookings/v2’ request (the backend is now or in the next few minutes, reserved)
-	By state from ‘status’ request (should have ‘true’ value)
-	By fields from ‘jobsLimit’request (maximum_jobs > running_jobs)
I think all these filters need to be applied. I'm right?
2.	Also: in some cases the 'isSimulator' input filter may be important. Do you mind if I add it to the input parameter? This could be:
auto qpu = xacc::getAccelerator("ibm", {{"backend","lowest-queue-count"}, {"n-qubits", N}, {"is-simulator", false}});
3.	What Is there enough to test this functionality? Add an example to xacc / Quantum / examples / base_api /?

Thanks

**Comment by flatslm** [comment]
At #451 Implemented backend selection functionality with a minimum size of the queue. At the same time, backends are filtered according to the following conditions:

    1. simulators backends
    2. backedns in state - false.
    3 if the "n-qubits" option is specified, then backends with the number of qbuits is less than the specified.
    if the "check-jobs-limit" option is specified, then the backends for which the number of allowed tasks is less than the number of running tasks.
