### ISSUE TITLE
How to compile in C++

### ISSUE THREAD

**Issue by tbcdebug** [eclipse/xacc#469]
I have been reading and following the documentation for a while. However, I haven't managed compile anything in C++. The xacc Python package works fine though. E.g., how can I compile the first C++ code snippet in [doc->Basics->Accelerator](https://xacc.readthedocs.io/en/latest/basics.html#accelerator)? (I used the docker so the files should be in standard locations.)

**Comment by tnguyen-ornl** [comment]
Hi,

There is an example (building an app executable based on XACC library) here that you might find useful:
https://github.com/ORNL-QCI/xacc_application_example/blob/master/CMakeLists.txt

**Comment by tbcdebug** [comment]
That solves it. Thanks! I really think this should the first thing in the doc after installation.
