### ISSUE TITLE
Invalid DirectedBoostGraph depth calculation

### ISSUE THREAD

**Issue by tnguyen-ornl** [eclipse/xacc#486]
Steps to reproduce:

```
  auto f = std::make_shared<Circuit>("foo");
  auto x = std::make_shared<X>(0);
  f->addInstruction(x);
  f->toGraph()->write(std::cout);
  std::cout << "Depth: " << f->depth() << "\n";
```

The depth result is -1 (should be 1 since there is 1 gate)

I think the issue is from the `DirectedBoostGraph::depth()` method.

**Comment by amccaskey** [comment]
I think it subtracts 2 due to the Initial and Final nodes. That's probably the source of error.

**Comment by tnguyen-ornl** [comment]
I think the logic of -2 is okay, but in this edge case of a single gate somehow `DirectedBoostGraph::depth()` returns 1 (it should return 3, I think).

**Comment by tnguyen-ornl** [comment]
@amccaskey checking other cases, I think you're right :) 
We shouldn't subtract 2  in `Circuit::depth()`
