### ISSUE TITLE
Port XACC (Build + Test) CI to GitHub Actions 

### ISSUE THREAD

**Issue by 1tnguyen** [eclipse/xacc#506]
This will remove dependency on the external GitLab runner.
Sometimes, the pipeline may fail sporadically, e.g., due to downloading Boost (https://code.ornl.gov/qci/xacc/-/jobs/1075894). 
Having CI in GitHub allows XACC committers to control the pipeline (e.g., rerun)

GitHub Actions is free for open-source repositories and we can run both Linux and Mac build.
My testing shows that it takes ~20 mins to build and test XACC (Linux and Mac pipelines can run simultaneously)

**Comment by 1tnguyen** [comment]
@amccaskey what do you think?

**Comment by amccaskey** [comment]
I think this is a great idea. I've looked into it before, but I always thought the free VMs would be too slow (at least, much slower than the CADES VMs we had). 

At this point, I don't think we have much choice. It is important to move away from the existing Gitlab CI/CD. This is probably the easiest next step, and we can update to better VMs later if possible.
