### ISSUE TITLE
Automatic plugin generation

### ISSUE THREAD

**Issue by amccaskey** [eclipse/xacc#53]
We need a way to generate a template C++ projects for various xacc extension points. Users can generate these template projects, and fill in pertinent functions to implement what they want. This gets users away from starting up all the boilerplate C++ and CMake code.

**Comment by amccaskey** [comment]
@czhao39 Hey Charles, would you care to issue a pull request for the plugin generation stuff you started. I'll take it from there. If you could, please PR into the `plugingenerator` branch

**Comment by jayjaybillings** [comment]
I recommend that you do this with Eclipse Project and Code Generators from CDT. I wouldn't write this from scratch.
________________________________

**Comment by czhao39** [comment]
I made the PR with some notes in the description. Sorry for the late response (I'm in Italy now).

**Comment by amccaskey** [comment]
@czhao39 no worries, thanks for the PR!
